### ISSUE TITLE
Lack of Information Regarding Rate Thresholds

### ISSUE THREAD

**Issue by williamtorres64** [DeDiamondPro/XCatch#13]
While researching and attempting to configure the plugin to detect cheating behavior based on ore acquisition rates, I discovered that the available documentation only provides examples such as "EMERALD_ORE: 12" or "IRON_ORE: 32." However, these examples do not specify the time interval over which these rates should be measured.

To effectively utilize the XCatch plugin and tailor it to our server's needs, it is crucial to have access to information about the time frame within which these rates should be observed. Without this crucial detail, it becomes challenging for server administrators to accurately detect cheating based on ore acquisition frequency.

Therefore, I kindly request that you consider addressing this issue by providing more explicit documentation regarding the time intervals required for the specified rates to trigger the cheating detection system. This would greatly assist server administrators in implementing the XCatch plugin effectively and ensuring fair gameplay.

**Comment by DeDiamondPro** [comment]
With the way XCatch works everything is linked to direction changes, including how long ore values are held. If players go in one direction for a while it will reset faster then when they switch a lot (which is an easy sign of xray).

So if you want to change how long these things are held there is the `direction-change-retention` setting in the advanced section. This will change how long a player has to mine in one direction before all tracked things (direction changes, amount of ores, ...) are reset.

**Comment by williamtorres64** [comment]
Oh, now I see, it works differently than I thought,
thank you!

**Comment by williamtorres64** [comment]
Actually, do you know if the mining method in this video will trigger the anti-cheat? It's a legit method involving constantly changing directions: https://youtu.be/6NqCSMvMGP4?t=37

**Comment by DeDiamondPro** [comment]
> Actually, do you know if the mining method in this video will trigger the anti-cheat? It's a legit method involving constantly changing directions: https://youtu.be/6NqCSMvMGP4?t=37

This will not get flagged because it does not trigger a direction change because, while yes the player mines in a new direction, they don't actually go in that direction.
