### ISSUE TITLE
False positive 0, 0, 0 spawnpoint

### ISSUE THREAD

**Issue by DarkChromaMC** [DeDiamondPro/XCatch#4]
Hello,

One of the players on my server got flagged for breaking unknown ores, at the 0 0 0 coordinate. I'm not sure how this is possible, however, this is what the GUI shows.

![image](https://user-images.githubusercontent.com/68839442/163941969-7d849b91-4423-4557-8b79-e30497fb252d.png)

**Comment by DeDiamondPro** [comment]
> Hello,
> 
> 
> 
> One of the players on my server got flagged for breaking unknown ores, at the 0 0 0 coordinate. I'm not sure how this is possible, however, this is what the GUI shows.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/68839442/163941969-7d849b91-4423-4557-8b79-e30497fb252d.png)
> 
> 

Hi, this is because you updated from 1.0 to 1.1 and 1.0 didn't keep ore or coordinate data, so it just shows old flags at 0 0 0
