### ISSUE TITLE
Silk touch mining diamonds

### ISSUE THREAD

**Issue by DarkChromaMC** [DeDiamondPro/XCatch#5]
Hello,

Would it be possible to bypass or ignore ores mined above a certain y-level? This would reduce false positives due to players mining a lot of silk-touched diamond ores at their base.

**Comment by DarkChromaMC** [comment]
An alternative approach would be to not include player-placed blocks/ores

**Comment by DeDiamondPro** [comment]
While the way XCatch works it shouldn't trigger on players placing piles of ores and then mining them but I'll look into adding something for y height

**Comment by DeDiamondPro** [comment]
Added in 1.1.1
