### ISSUE TITLE
DiscordSRV Problem

### ISSUE THREAD

**Issue by dgal1992** [DeDiamondPro/XCatch#6]
It seems there's a problem with newer channel ID's from discord as they now exceed 18 characters. In the plugin it states the exact length should be 18 so newer channels don't get sent any info to them. 

Looks like line 117 on Utils.java where the range of char length needs to be increased. 

Sorry if this is a lecture just trying to help where I can. 

Cheers

**Comment by DeDiamondPro** [comment]
Thanks for this information, I’ll make a quick fix tomorrow, I completely forgot discord increased the length

**Comment by DeDiamondPro** [comment]
Fixed in version 1.1.2, thanks for the detailed report tho!

**Comment by dgal1992** [comment]
No problem thanks for the swift fix!
