### ISSUE TITLE
Change amount of ores needed to be mined

### ISSUE THREAD

**Issue by TomSipsOnCurry** [DeDiamondPro/XCatch#7]
How would I make the amount of diamonds required to be mined for the server to flag them be decreased? I made the engine mode 1 on my paper server, but I still want to use this. Im sorry if I did this in the wrong place.

**Comment by DeDiamondPro** [comment]
Hi, to do this you would need to go to config.yml inside the xcatch folder inside the plugin folder, scroll down to, the advanced section and then you should see the `rare-ore` field where you can modify ores and amounts

**Comment by TomSipsOnCurry** [comment]
How come in the config it says 16 diamond deepslate ores but in the discord message it says 20? how does it work?
![image](https://user-images.githubusercontent.com/78724847/194414632-272185bd-7adf-47ae-93a0-95e1efe03768.png)

**Comment by DeDiamondPro** [comment]
> How come in the config it says 16 diamond deepslate ores but in the discord message it says 20? how does it work? ![image](https://user-images.githubusercontent.com/78724847/194414632-272185bd-7adf-47ae-93a0-95e1efe03768.png)

This is because XCatch also analyzes how a player mines and uses that as an additional threshold, when the player had mined 16 diamonds this treshold was probably not met while when he mined 20 it was, this is also what sets XCatch appart frorm plugins like ore announcer

**Comment by TomSipsOnCurry** [comment]
oh nice ty
