### ISSUE TITLE
AntiCheatReplay support

### ISSUE THREAD

**Issue by erxson** [DeDiamondPro/XCatch#9]
https://github.com/JustinDevB/AntiCheatReplay
It can be useful if an annoying player or project administration asks for video evidence that a person used Baritone or Xray. And just a cool feature.

**Comment by DeDiamondPro** [comment]
I'll look into it, in the meantime you can use https://www.spigotmc.org/resources/advancedreplay-1-8-1-19.52849/ and add a command in the config to start recording a player, or use the plugin you suggested if it has a command for that.

**Comment by erxson** [comment]
Oh, forgot about commands. I'm sorry

**Comment by erxson** [comment]
The disadvantage of the command is that it is impossible to change the name of the entry.
report {player} {player}-{ore}-{amount}-{x}/{y}/{z}
replay start {player} {player}-{ore}-{amount}-{x}/{y}/{z}
These commands create records with just player name
